#!/bin/bash

SOURCE_DIR="tdesktop"

function pushToHub {
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push "$1"
}

if [ ! -d tdesktop ]; then
    git clone -b dev https://github.com/telegramdesktop/tdesktop.git $SOURCE_DIR
fi

if [ $# -eq 0 ]
then
    docker build . -t telegramdesktop/linux_build
elif [ "$1" = "dependencies2" ]; then
    # Use the image generated by dependencies
    docker build . -t telegramdesktop/linux_build --build-arg STAGE="$1" --build-arg FROM=telegramdesktop/docker_linux_dependencies1
    
    status=$?
    if [ $status -ne 0 ]; then
        exit $status
    fi
    
    pushToHub telegramdesktop/linux_build
else 
    docker pull telegramdesktop/docker_linux_dependencies1
    docker build . -t telegramdesktop/docker_linux_dependencies1 --build-arg STAGE="$1"
    
    status=$?
    if [ $status -ne 0 ]; then
        exit $status
    fi
    
    pushToHub telegramdesktop/docker_linux_dependencies1
fi
