if [ ! -d tdesktop ]; then
    git clone -b dev https://github.com/telegramdesktop/tdesktop.git
fi

if [ $# -eq 0 ]
then
    docker build . -t telegramdesktop/tdesktop
elif [ $1 = "dependencies2" ]; then
    # Use the image generated by dependencies
    docker build . -t telegramdesktop/tdesktop --build-arg STAGE=$1 --build-arg FROM=telegramdesktop/docker_linux_dependencies1
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push telegramdesktop/tdesktop
else 
    docker pull telegramdesktop/docker_linux_dependencies1
    docker build . -t telegramdesktop/docker_linux_dependencies1 --build-arg STAGE=$1
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push telegramdesktop/docker_linux_dependencies1
fi
