if [ ! -d tdesktop ]; then
    git clone -b dev https://github.com/telegramdesktop/tdesktop.git
fi

if [ $# -eq 0 ]
then
    docker build . -t telegramdesktop/tdesktop
elif [ $1 = "dependencies2" ]; then
    # Use the image generated by dependencies
    docker build . -t telegramdesktop/tdesktop --build-arg STAGE=$1 --build-arg FROM=telegramdesktop/docker_linux_dependencies1
else 
    docker build . -t telegramdesktop/docker_linux_dependencies1 --build-arg STAGE=$1
fi
